CREATE TABLE DBO_SAMPLE.REF_CURRENCY
(
    ID          INT PRIMARY KEY         NOT NULL AUTO_INCREMENT,
    NAME        VARCHAR(30),
    CODE        VARCHAR(3),
    CREATED_BY  VARCHAR(64)             NOT NULL,
    CREATED_ON  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(64)             NOT NULL,
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IS_DELETED  BOOLEAN   DEFAULT FALSE NOT NULL
);
